aws_region              = "eu-north-1"
project_name            = "aws-modular-infra"
environment             = "dev"
vpc_cidr                = "10.0.0.0/16"
public_subnet_cidrs     = ["10.0.1.0/24", "10.0.2.0/24"]
private_subnet_cidrs    = ["10.0.10.0/24", "10.0.11.0/24"]
instance_type           = "t3.micro"
ami_id                  = ""
key_name                = "assignment3-key"
my_ip_cidr              = "59.103.246.18/32"
state_lock_table_name   = "aws-modular-infra-dev-tf-locks"
ec2_s3_role_name        = "aws-modular-infra-dev-ec2-s3-role"
asg_min_size            = 1
asg_max_size            = 3
asg_desired_capacity    = 2
scale_out_cpu_threshold = 60
scale_in_cpu_threshold  = 20
